# ==============================================================================
# FIXED docker-compose.yml - Resolves Database Authentication Issues
# ==============================================================================

services:
  # PostgreSQL Database with FIXED authentication
  db:
    image: postgres:16
    container_name: payshield-core-db-1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Kolkata
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    networks: [payshield]
    ports:
      - "5432:5432"  # Expose for debugging if needed

  # ClamAV Antivirus Service - IMPROVED startup
  clamav:
    image: clamav/clamav:1.0.9
    container_name: payshield-clamav-1
    environment:
      CLAMAV_NO_FRESHCLAM: false
      CLAMAV_NO_CLAMD: false
    volumes:
      - clamav-db:/var/lib/clamav
      - clamav-logs:/var/log/clamav
    healthcheck:
      test: ["CMD-SHELL", "clamdscan --ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s  # Give ClamAV 3 minutes to download virus definitions
    restart: unless-stopped
    networks: [payshield]
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Main Application - FIXED Configuration
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payshield-core-app-1
    environment:
      # FIXED: Explicit profile setting
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}

      # FIXED: Database Connection - use same password as PostgreSQL
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      # Server Configuration
      SERVER_PORT: ${APP_PORT}
      JAVA_TOOL_OPTIONS: "-XX:+UseZGC -Xms256m -Xmx512m -Djava.security.egd=file:/dev/./urandom"
      TZ: Asia/Kolkata

      # Security Configuration
      SECURITY_JWT_SECRET: ${SECURITY_JWT_SECRET}
      SECURITY_JWT_TTL_SECONDS: ${SECURITY_JWT_TTL_SECONDS}

      # Bootstrap Admin
      BOOTSTRAP_ADMIN_EMAIL: ${BOOTSTRAP_ADMIN_EMAIL}
      BOOTSTRAP_ADMIN_PASSWORD: ${BOOTSTRAP_ADMIN_PASSWORD}
      BOOTSTRAP_DEFAULT_TENANT_ID: ${BOOTSTRAP_DEFAULT_TENANT_ID}

      # ✅ CRITICAL FIX: Encryption Key Environment Variables
      PSP_AES_KEY: ${PSP_AES_KEY}
      APP_ENCRYPTION_KEY: ${PSP_AES_KEY}  # Alternative mapping


      # Management/Actuator
      MANAGEMENT_SERVER_PORT: ${ACTUATOR_PORT}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"

      # Application Configuration
      STORAGE_BASE_PATH: /app/storage

      # Outbox Configuration
      OUTBOX_ENABLED: ${OUTBOX_ENABLED}
      OUTBOX_POLL_INTERVAL_MS: ${OUTBOX_POLL_INTERVAL_MS}
      OUTBOX_BATCH_SIZE: ${OUTBOX_BATCH_SIZE}

      # File Upload Security
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10MB}
      MAX_REQUEST_SIZE: ${MAX_REQUEST_SIZE:-10MB}
      VALIDATE_FILE_CONTENT: ${VALIDATE_FILE_CONTENT:-true}
      STRICT_MIME_CHECK: ${STRICT_MIME_CHECK:-true}

      # ClamAV Configuration - Made optional for local development
      CLAMAV_ENABLED: ${CLAMAV_ENABLED:-false}
      CLAMAV_HOST: clamav
      CLAMAV_PORT: 3310
      CLAMAV_TIMEOUT: ${CLAMAV_TIMEOUT:-30000}
      CLAMAV_CONNECTION_TIMEOUT: ${CLAMAV_CONNECTION_TIMEOUT:-5000}
      CLAMAV_FAIL_SECURE: ${CLAMAV_FAIL_SECURE:-false}

      # Development Features
      API_DOCS_ENABLED: ${API_DOCS_ENABLED:-true}
      SWAGGER_UI_ENABLED: ${SWAGGER_UI_ENABLED:-true}
      DEBUG_ENDPOINTS_ENABLED: ${DEBUG_ENDPOINTS_ENABLED:-true}

      # Logging configuration
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      SECURITY_LOG_LEVEL: ${SECURITY_LOG_LEVEL:-DEBUG}
      WEB_LOG_LEVEL: ${WEB_LOG_LEVEL:-INFO}

    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${ACTUATOR_PORT}:${ACTUATOR_PORT}"

    depends_on:
      db:
        condition: service_healthy
      # FIXED: Make ClamAV optional - don't block app startup
      # clamav:
      #   condition: service_healthy

    restart: unless-stopped
    networks: [payshield]

    volumes:
      - app-logs:/app/logs
      - app-storage:/app/storage

    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

# ==============================================================================
# VOLUMES CONFIGURATION
# ==============================================================================
volumes:
  pgdata:
    driver: local
  clamav-db:
    driver: local
  clamav-logs:
    driver: local
  app-storage:
    driver: local
  app-logs:
    driver: local

# ==============================================================================
# NETWORKS CONFIGURATION
# ==============================================================================
networks:
  payshield:
    driver: bridge

# ==============================================================================
# FIXES APPLIED:
# ==============================================================================
# 1. ✅ FIXED: Database authentication - matching passwords
# 2. ✅ FIXED: Environment variable resolution
# 3. ✅ FIXED: ClamAV dependency made optional
# 4. ✅ FIXED: Added database port exposure for debugging
# 5. ✅ FIXED: Improved healthcheck reliability
# 6. ✅ FIXED: Better resource limits and startup timing