spring:
  application:
    name: payshield-core
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:}
    password: ${MAIL_PASS:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payshield}
    username: ${DB_USERNAME:payshield}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:10}
      minimum-idle: ${DB_POOL_MIN:2}
      connection-timeout: ${DB_POOL_TIMEOUT_MS:30000}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        jdbc.lob.non_contextual_creation: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Enhanced file upload security - Step 5
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
      resolve-lazily: true
      file-size-threshold: 0
      location: ${TEMP_DIR:${java.io.tmpdir}}/payshield

  mvc:
    async:
      request-timeout: 60000

server:
  port: ${APP_PORT:2406}
  server-header:
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

  # FIXED: Use correct Spring Boot 3.x property name
  max-http-request-header-size: ${MAX_HEADER_SIZE:8KB}

  # Modern Spring Boot 3.x Tomcat configuration
  tomcat:
    connection-timeout: 20s
    keep-alive-timeout: 20s
    max-connections: 8192
    accept-count: 100
    threads:
      max: 200
      min-spare: 10

management:
  server:
    port: ${ACTUATOR_PORT:9090}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
    info:
      env:
        enabled: false

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
    ttl-seconds: ${SECURITY_JWT_TTL_SECONDS:3600}

bootstrap:
  admin:
    email: ${BOOTSTRAP_ADMIN_EMAIL}
    password: ${BOOTSTRAP_ADMIN_PASSWORD}
  defaultTenantId: ${BOOTSTRAP_DEFAULT_TENANT_ID:00000000-0000-0000-0000-000000000001}

# Application configuration with Step 5 enhancements
app:
  outbox:
    enabled: ${OUTBOX_ENABLED:true}
    poll-ms: ${OUTBOX_POLL_INTERVAL_MS:5000}
    batch-size: ${OUTBOX_BATCH_SIZE:50}

  storage:
    basePath: ${STORAGE_BASE_PATH:var/storage}

  # File Upload Security Configuration - Step 5
  upload:
    max-file-size: ${MAX_FILE_SIZE:10MB}
    allowed-mime-types:
      - application/pdf
    validate-content: ${VALIDATE_FILE_CONTENT:true}
    strict-mime-check: ${STRICT_MIME_CHECK:true}

  # ClamAV Antivirus Configuration - Step 5
  clamav:
    enabled: ${CLAMAV_ENABLED:false}
    host: ${CLAMAV_HOST:clamav}
    port: ${CLAMAV_PORT:3310}
    timeout: ${CLAMAV_TIMEOUT:30000}
    connection-timeout: ${CLAMAV_CONNECTION_TIMEOUT:5000}
    fail-secure: ${CLAMAV_FAIL_SECURE:false}

# Step 11: OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:true}
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    # Enhanced Swagger UI features
    display-request-duration: true
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
    use-root-path: true
    try-it-out-enabled: true
    filter: true
    # OAuth2 configuration placeholder (for future MFA integration)
    oauth2-redirect-url: /swagger-ui/oauth2-redirect.html
  # Show actual class names instead of generic "Object"
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  # Group endpoints by tags
  group-configs:
    - group: 'authentication'
      display-name: 'Authentication APIs'
      paths-to-match: '/auth/**'
    - group: 'invoice-processing'
      display-name: 'Invoice Processing APIs'
      paths-to-match: '/invoices/**'
    - group: 'case-management'
      display-name: 'Case Management APIs'
      paths-to-match: '/cases/**'
    - group: 'administration'
      display-name: 'Administration APIs'
      paths-to-match: '/outbox/**'

# Logging configuration - container-friendly paths
logging:
  level:
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql: ERROR
    org.springframework.web: ${WEB_LOG_LEVEL:WARN}
    org.springframework.web.cors: DEBUG
    com.payshield.frauddetector.infrastructure.security: INFO
    com.payshield.frauddetector.api.InvoiceController: INFO
    org.springframework.web.multipart: ${MULTIPART_LOG_LEVEL:WARN}
    org.apache.tika: ${TIKA_LOG_LEVEL:WARN}
    # Reduce Tika external parser noise
    org.apache.tika.parser.external: WARN
    org.apache.tika.parser.ocr: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:/app/logs/payshield.log}
  logback:
    rollingpolicy:
      max-file-size: 50MB
      total-size-cap: 500MB
      max-history: 30

# OpenTelemetry configuration
otel:
  resource:
    attributes: service.name=${spring.application.name:payshield-core}
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:}

---
# Local development profile
spring:
  config:
    activate:
      on-profile: local

  # Local development database
  datasource:
    url: jdbc:postgresql://db:5432/payshield
    username: payshield
    password: payshield

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 2406

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret: dev_secret_key_123456789012345678901234567890
    ttl-seconds: 3600

bootstrap:
  admin:
    email: admin@yourcompany.com
    password: 8eXlClc9INVRyGQ8
  defaultTenantId: 00000000-0000-0000-0000-000000000001

# Local development settings - Step 5 & 11
app:
  clamav:
    enabled: true  # Enable ClamAV in local for testing
    fail-secure: false
  upload:
    strict-mime-check: true
    validate-content: true

# Step 11: Full Swagger UI enabled in local development
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    # Local development enhancements
    try-it-out-enabled: true
    filter: true
    display-request-duration: true
    # Show all endpoint groups
    urls-primary-name: 'PayShield API v1.0'

# Enhanced local development logging
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.web.multipart: DEBUG
    com.payshield.frauddetector.config: DEBUG
    com.payshield.frauddetector.config.JwtAuthFilter: DEBUG
    com.payshield.frauddetector.config.RequestLoggingFilter: DEBUG
    com.payshield.frauddetector.domain.DetectionEngine: DEBUG
    com.payshield.frauddetector.application.InvoiceDetectionService: DEBUG
    com.payshield.frauddetector.infrastructure.parser.TikaPdfParser: DEBUG
    com.payshield.frauddetector.infrastructure.security: DEBUG
    org.apache.tika: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.filter: DEBUG
    # Reduce external parser noise in local too
    org.apache.tika.parser.external: WARN
    org.apache.tika.parser.ocr: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: # No file logging in local development

---
# Production profile with full security enabled
spring:
  config:
    activate:
      on-profile: production

# Production security settings
app:
  clamav:
    enabled: true
    fail-secure: true
  storage:
    scan-on-upload: true
  upload:
    strict-mime-check: true
    validate-content: true

server:
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

# Step 11: Disable Swagger UI in production for security
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Production logging
logging:
  level:
    root: WARN
    com.payshield.frauddetector: INFO
    com.payshield.frauddetector.infrastructure.security: INFO
    com.payshield.frauddetector.api.InvoiceController: INFO
    # Completely silence external parser logs in production
    org.apache.tika.parser.external: ERROR
    org.apache.tika.parser.ocr: ERROR
  file:
    name: /app/logs/payshield.log

---
# Step 11: Testing profile for automated tests
spring:
  config:
    activate:
      on-profile: test

  # In-memory H2 database for fast tests
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  # Disable external integrations in tests
  flyway:
    enabled: false

# Test configuration
app:
  clamav:
    enabled: false
  upload:
    validate-content: false
    strict-mime-check: false

# Disable Swagger in tests
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Minimal logging in tests
logging:
  level:
    root: WARN
    com.payshield.frauddetector: INFO
    org.apache.tika: ERROR
    org.springframework: WARN